on: [push]

name: Integration test

env:
  RUST_BACKTRACE: 1

jobs:
  install_bash:
    name: Install (Bash)
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          - windows-latest
    steps:
      - name: Debug prints
        run: |
          echo "SHELL: ${SHELL}"
      - name: Install Hygeia
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.sh | sh
      - name: Hygeia Information
        run: |
          hygeia --version
          hygeia list

  install_zsh:
    name: Install (Zsh)
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: zsh --errexit -l {0}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          # - windows-latest
    steps:
      - name: Debug prints
        run: |
          echo "SHELL: ${SHELL}"
      - name: Install Hygeia (Zsh)
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.sh | sh
          cp ~/.zshrc ~/.zshenv
      - name: Hygeia Information
        run: |
          hygeia --version
          hygeia list

  install_powershell:
    name: Install (PowerShell)
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          - windows-latest
    steps:
      - name: Install Hygeia (PowerShell)
        run: |
          . { iwr -useb https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.ps1 } | iex
      - name: Hygeia Information
        run: |
          echo "SHELL: ${SHELL}"
          hygeia --version
          hygeia list
