on: [push]

# FIXME: PowerShell on Ubuntu: Cannot find 'Document' directory (https://github.com/nbigaouette/hygeia/runs/1433106224?check_suite_focus=true)
# FIXME: PowerShell on macOS: Cannot find binary after installation (https://github.com/nbigaouette/hygeia/runs/1433106248?check_suite_focus=true)
# FIXME: PowerShell on Windows: Cannot find binary after installation (https://github.com/nbigaouette/hygeia/runs/1433106268?check_suite_focus=true)

name: Integration test

env:
  RUST_BACKTRACE: 1

jobs:
  install_bash:
    name: Install (Bash)
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -leo pipefail {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          # - windows-latest
    steps:
      - name: Debug prints
        run: |
          echo "SHELL: ${SHELL}"
      - name: Install Hygeia
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.sh | sh
      - name: Hygeia Information
        run: |
          hygeia --version
          hygeia list

  install_zsh:
    name: Install (Zsh)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          # - windows-latest
    steps:
      - name: Install extra packages (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install zsh
      - name: Debug prints
        shell: zsh --errexit -l {0}
        run: |
          echo "SHELL: ${SHELL}"
      - name: Install Hygeia (Zsh)
        shell: zsh --errexit -l {0}
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.sh | sh
          cp ~/.zshrc ~/.zshenv
      - name: Hygeia Information
        shell: zsh --errexit -l {0}
        run: |
          hygeia --version
          hygeia list
  # install_powershell:
  #   name: Install (PowerShell)
  #   runs-on: ${{ matrix.os }}
  #   defaults:
  #     run:
  #       shell: pwsh
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-16.04
  #         - ubuntu-18.04
  #         - ubuntu-20.04
  #         - macOS-10.15
  #         - macOS-11.0
  #         - windows-latest
  #   steps:
  #     - name: Install Hygeia (PowerShell)
  #       run: |
  #         . { iwr -useb https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.ps1 } | iex
  #     - name: Hygeia Information
  #       run: |
  #         echo "SHELL: ${SHELL}"
  #         echo $profile
  #         echo $env:Path
  #         echo $env:PATH
  #         Get-Content $profile
  #         hygeia --version
  #         hygeia list
