on: [push]

name: Integration test

env:
  RUST_BACKTRACE: 1

jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          - windows-latest
        shell:
          - bash -leo pipefail {0}
          - zsh --errexit -l {0}
          - pwsh
    steps:
      - name: Install extra packages (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install zsh
      # - name: Install extra packages (macOS)
      #   if: contains(matrix.os, 'macOS')
      #   run: |
      #     brew install zsh
      #     brew cask install powershell

      - name: Install Hygeia (PowerShell)
        shell: ${{ matrix.shell }}
        if: contains(matrix.shell, 'pwsh')
        run: |
          . { iwr -useb https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.ps1 } | iex
      - name: Install Hygeia (Zsh)
        shell: ${{ matrix.shell }}
        if: contains(matrix.shell, 'zsh')
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.sh | sh
          cp ~/.zshrc ~/.zshenv
      - name: Install Hygeia (Bash)
        shell: ${{ matrix.shell }}
        if: contains(matrix.shell, 'bash')
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.sh | sh

      - name: Hygeia Information
        shell: ${{ matrix.shell }}
        run: |
          echo "SHELL: ${SHELL}"
          hygeia --version
          hygeia list
