on: [push]

name: Integration test

env:
  RUST_BACKTRACE: 1

jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11.0
          # - windows-latest
    steps:
      - name: Install Hygeia (Unix)
        if: "matrix.os != 'windows-latest'"
        run: |
          curl -fsSL https://raw.githubusercontent.com/nbigaouette/hygeia/master/install.sh | sh
          cp ~/.zshrc ~/.zshenv

      - name: Install (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          . { iwr -useb https://raw.githubusercontent.com/nbigaouette/hygeia/readme-instructions/install.ps1 } | iex

      - name: Install extra packages (macOS)
        if: contains(matrix.os, 'macOS')
        run: |
          brew cask install powershell

      - name: Install extra packages (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install zsh powershell

      - name: Hygeia Information (Bash)
        if: "!contains(matrix.os , 'windows')"
        shell: bash -leo pipefail {0}
        run: |
          echo "SHELL: ${SHELL}"
          echo "HOME: ${HOME}"
          pwd
          ls -lah ~
          hygeia --version
          hygeia list

      - name: Hygeia Information (Zsh)
        if: "!contains(matrix.os , 'windows')"
        shell: zsh --errexit -l {0}
        run: |
          echo "SHELL: ${SHELL}"
          echo "HOME: ${HOME}"
          pwd
          ls -lah ~
          hygeia --version
          hygeia list

      - name: Hygeia Information (Powershell)
        # if: contains(matrix.os, 'windows')
        shell: pwsh
        run: |
          echo "SHELL: ${SHELL}"
          hygeia --version
          hygeia list
